# Ejercicio 1

Obtener la descomposición de Cholesky de la siguiente matriz.

$A=\begin{pmatrix}
4 & 2 & 2 & 4 \\
2 & 5 & 7 & 0\\
2 & 7 & 19 & 11 \\
4 & 0 & 11 & 25
\end{pmatrix}$

In [3]:
#Definamos la matriz
A1=cbind(c(4,2,2,4),c(2,5,7,0),c(2,7,19,11),c(4,0,11,25)) #Metodo con el comando indexar donde cada vector entra como una columna a una matriz
A2=matrix(c(4,2,2,4,2,5,7,0,2,7,19,11,4,0,11,25),4,4)  #Metodo con el comando matrix donde entregamos los datos y las dimensiones de la matriz
A1
A2

[,1] [,2] [,3] [,4]
[1,] 4    2     2    4  
[2,] 2    5     7    0  
[3,] 2    7    19   11  
[4,] 4    0    11   25

[,1] [,2] [,3] [,4]
[1,] 4    2     2    4  
[2,] 2    5     7    0  
[3,] 2    7    19   11  
[4,] 4    0    11   25

In [5]:
g=chol(A1)
g
t(g)%*%g

[,1] [,2] [,3] [,4]
[1,] 2    1    1     2  
[2,] 0    2    3    -1  
[3,] 0    0    3     4  
[4,] 0    0    0     2

[,1] [,2] [,3] [,4]
[1,] 4    2     2    4  
[2,] 2    5     7    0  
[3,] 2    7    19   11  
[4,] 4    0    11   25

Resuelva el sistema $Ax=b$, para

$A=\begin{pmatrix}
4 & 2 & 2 & 4 \\
2 & 5 & 7 & 0\\
2 & 7 & 19 & 11 \\
4 & 0 & 11 & 25
\end{pmatrix}$     ,$\quad$ $b=\begin{pmatrix}
-1 \\
1 \\
\frac{5}{2}\\
\frac{1}{2}
\end{pmatrix}$

![Cholesky](Cholesky.png)


In [10]:
#Creamos las matrices.
A2=matrix(c(4,2,2,4,2,5,7,0,2,7,19,11,4,0,11,25),4,4)  #matrix(vector,filas,columnas)
b1 = matrix(c(-1,1,5/2,1/2),4,1)
b2=c(-1,1,5/2,1/2)
#b1
#b2

[1] -1.0  1.0  2.5  0.5

In [12]:
g=chol(A2)
gt=t(g)
z=solve(gt)%*%b1 #solve(matriz) entrega la inversa de una matriz, con lo cual acá estamos resolviendo el sistemga G'z=b de la forma z=b*G'^{-1}
z

[,1]  
[1,] -0.500
[2,]  0.750
[3,]  0.250
[4,]  0.625

In [13]:
x=solve(g)%*%z
A1%*%x

[,1]
[1,] -1.0
[2,]  1.0
[3,]  2.5
[4,]  0.5

# Ejercicio 2

Hagamos regresión con Choelesky para la siguiente muestra.



In [18]:
tabla=read.table('Ejercicio_2_tabla',T) #read.table('nombre_del_archivo',Tiene header?)

In [19]:
tabla

Y  x1 x2 x3
1 12  4  5  6
2 23  8  9 12
3 41 12  3 23
4 89 11 17 21
5 18  8 19 39
6 39 19 21 45
7 56  9 22 42
8  9 13  9 18

In [22]:
X1=cbind('unos'=rep(1,8),tabla[,2:4])  #Creando matriz de diseño
X1

unos x1 x2 x3
1 1     4  5  6
2 1     8  9 12
3 1    12  3 23
4 1    11 17 21
5 1     8 19 39
6 1    19 21 45
7 1     9 22 42
8 1    13  9 18

In [23]:
y1=tabla['Y'] #data frame
y1

Y 
1 12
2 23
3 41
4 89
5 18
6 39
7 56
8  9

In [24]:
w1=t(X1)%*%y1
w1

ERROR: Error in t(X1) %*% y1: requires numeric/complex matrix/vector arguments


### El problema anterior se debe a que la multiplicación pide que sean matrices las que se multipliquen y no reconoce a y1 como una matriz

In [30]:
X2=as.matrix(X1) #Trabajar todo como matriz as.nombre_objeto(Objeto_original)
colnames(X2)=NULL #Acá meramente estetico
X2

[,1] [,2] [,3] [,4]
[1,] 1     4    5    6  
[2,] 1     8    9   12  
[3,] 1    12    3   23  
[4,] 1    11   17   21  
[5,] 1     8   19   39  
[6,] 1    19   21   45  
[7,] 1     9   22   42  
[8,] 1    13    9   18

In [31]:
y2=tabla[,1] #Trabajar todo como matriz
y2

[1] 12 23 41 89 18 39 56  9

In [32]:
t(X2)%*%X2 #Matriz claramente simetrica y definida positiva

[,1] [,2] [,3] [,4]
[1,]   8    84  105  206
[2,]  84  1020 1181 2406
[3,] 105  1181 1771 3336
[4,] 206  2406 3336 6784

![Estimacion](estimacion_beta.png)


In [33]:
w=t(X2)%*%y2 
G=chol(t(X2)%*%X2) #Matriz triangular superior
G

[,1]     [,2]     [,3]      [,4]    
[1,] 2.828427 29.69848 37.123106 72.83200
[2,] 0.000000 11.74734  6.682364 20.68553
[3,] 0.000000  0.00000 18.660681 26.47394
[4,] 0.000000  0.00000  0.000000 18.72803

In [37]:
z=forwardsolve(t(G),w) #La función forwardsolve aprovecha el hecho de que una matriz es triangular
z

[,1]     
[1,] 101.46982
[2,]  16.64207
[3,]  26.73625
[4,] -16.62288

In [38]:
b=backsolve(G,z) #calculo del vector de coeficientes de regresion (beta gorro)
b

[,1]      
[1,]  8.1911264
[2,]  1.4482906
[3,]  2.6919893
[4,] -0.8875937

![RSS](RSS.png)

In [39]:
#calculo de la suma de cuadrados del error (RSS)
sse=t(y2)%*%y2-t(z)%*%z
sse 

[,1]    
[1,] 3772.769

In [40]:
#calculo del vector de predicciones a partir de la muestra
yhat=X2%*%b
yhat

[,1]    
[1,] 22.11867
[2,] 33.35423
[3,] 13.23193
[4,] 51.24667
[5,] 36.30909
[6,] 52.29871
[7,] 43.17057
[8,] 35.27012

In [41]:
#Podemos calcular la matriz de covarianza
cov=t(solve(G))%*%solve(G)
cov

[,1]        [,2]       [,3]        [,4]       
[1,]  0.12500000 -0.3160129 -0.13550820  0.05448148
[2,] -0.31601286  0.8061594  0.33998376 -0.14207039
[3,] -0.13550820  0.3399838  0.15070076 -0.06156841
[4,]  0.05448148 -0.1420704 -0.06156841  0.03492952

# Ejercicio 3

### Programe una versión de función sweep 

In [42]:
# Función sweep
sweep = function(A, k) {
    B = matrix(0,dim(A)[1],dim(A)[1])
    n=dim(A)[1]
    B[k,k] = 1/A[k,k]
    for (i in 1:n){
        if (i != k){
            B[i,k]=-A[i,k]/A[k,k]
        }
    }
    for (j in 1:n){
        if (j != k){
            B[k,j]=A[k,j]/A[k,k]
        }
    }
    for (i in 1:n){
        for (j in 1:n){
            if (i != k & j != k){
                B[i,j]= A[i,j]-(A[i,k]*A[k,j])/A[k,k]
            }
        }
    }
    return(B)
}


# Ejercicio 4

Pruebe que la función anterior funciona bien con la siguiente matriz y revise las propiedades vistas en clases.

![Sweep](propiedades_operador_sweep.png)


$M=\begin{pmatrix}
30 & 16 & 46 \\
16 & 10 & 26 \\
46 & 26 & 72
\end{pmatrix}$  

In [43]:
M=matrix(c(30,16,46,16,10,26,46,26,72),3)
M

[,1] [,2] [,3]
[1,] 30   16   46  
[2,] 16   10   26  
[3,] 46   26   72

In [44]:
library('fastmatrix')

In [45]:
sweep(M,1)

[,1]        [,2]      [,3]    
[1,]  0.03333333 0.5333333 1.533333
[2,] -0.53333333 1.4666667 1.466667
[3,] -1.53333333 1.4666667 1.466667

In [46]:
sweep.operator(M,1)

[,1]        [,2]      [,3]    
[1,]  0.03333333 0.5333333 1.533333
[2,] -0.53333333 1.4666667 1.466667
[3,] -1.53333333 1.4666667 1.466667

In [47]:
sweep(M,2)

[,1] [,2] [,3]
[1,] 4.4  -1.6 4.4 
[2,] 1.6   0.1 2.6 
[3,] 4.4  -2.6 4.4

In [48]:
sweep.operator(M,2)

[,1] [,2] [,3]
[1,] 4.4  -1.6 4.4 
[2,] 1.6   0.1 2.6 
[3,] 4.4  -2.6 4.4

In [49]:
sweep(M,3)

[,1]       [,2]       [,3]       
[1,]  0.6111111 -0.6111111 -0.63888889
[2,] -0.6111111  0.6111111 -0.36111111
[3,]  0.6388889  0.3611111  0.01388889

In [54]:
sweep.operator(M,3)

[,1]       [,2]       [,3]       
[1,]  0.6111111 -0.6111111 -0.63888889
[2,] -0.6111111  0.6111111 -0.36111111
[3,]  0.6388889  0.3611111  0.01388889

In [52]:
sweep(sweep(M,1),2)

[,1]       [,2]       [,3]        
[1,]  0.2272727 -0.3636364 1.000000e+00
[2,] -0.3636364  0.6818182 1.000000e+00
[3,] -1.0000000 -1.0000000 5.329071e-15

In [55]:
sweep(sweep(M,2),1)

[,1]       [,2]       [,3]        
[1,]  0.2272727 -0.3636364 1.000000e+00
[2,] -0.3636364  0.6818182 1.000000e+00
[3,] -1.0000000 -1.0000000 7.105427e-15

Intentemos calcular la inversa de la matriz con sweep

In [63]:
inv_M=sweep.operator(sweep.operator(sweep.operator(M,3),2),1)
inv_M

ERROR: Error in sweep.operator(sweep.operator(M, 3), 2): only implemented for symmetric matrices.


In [64]:
inv_sweep = function (A) {
n = dim(A)[1]
B = A
for (i in 1:n){
B = sweep(B,i)
}
return(B)
}

In [67]:
sweep(sweep(sweep(M,2),1),3)

[,1]          [,2]          [,3]         
[1,]  1.407375e+14  1.407375e+14 -1.407375e+14
[2,]  1.407375e+14  1.407375e+14 -1.407375e+14
[3,] -1.407375e+14 -1.407375e+14  1.407375e+14

In [68]:
inv_sweep(M)

[,1]        [,2]        [,3]       
[1,]  1.8765e+14  1.8765e+14 -1.8765e+14
[2,]  1.8765e+14  1.8765e+14 -1.8765e+14
[3,] -1.8765e+14 -1.8765e+14  1.8765e+14

In [69]:
solve(M)

ERROR: Error in solve.default(M): sistema es computacionalmente singular: número de condición recíproco = 3.85494e-18


In [70]:
help(solve)

solve                   package:base                   R Documentation

_S_o_l_v_e _a _S_y_s_t_e_m _o_f _E_q_u_a_t_i_o_n_s

_D_e_s_c_r_i_p_t_i_o_n:

     This generic function solves the equation ‘a %*% x = b’ for ‘x’,
     where ‘b’ can be either a vector or a matrix.

_U_s_a_g_e:

     solve(a, b, ...)
     
     ## Default S3 method:
     solve(a, b, tol, LINPACK = FALSE, ...)
     
_A_r_g_u_m_e_n_t_s:

       a: a square numeric or complex matrix containing the
          coefficients of the linear system.  Logical matrices are
          coerced to numeric.

       b: a numeric or complex vector or matrix giving the right-hand
          side(s) of the linear system.  If missing, ‘b’ is taken to be
          an identity matrix and ‘solve’ will return the inverse of
          ‘a’.

     tol: the tolerance for detecting linear dependencies in the
          columns of ‘a’.  The default is ‘.Machine$double.eps’. Not
          currently used with complex matrices ‘a’.

 LINPACK: logical.  Defunct and ignored.

     ...: further arguments passed to or from other methods

_D_e_t_a_i_l_s:

     ‘a’ or ‘b’ can be complex, but this uses double complex arithmetic
     which might not be available on all platforms.

     The row and column names of the result are taken from the column
     names of ‘a’ and of ‘b’ respectively.  If ‘b’ is missing the
     column names of the result are the row names of ‘a’.  No check is
     made that the column names of ‘a’ and the row names of ‘b’ are
     equal.

     For back-compatibility ‘a’ can be a (real) QR decomposition,
     although ‘qr.solve’ should be called in that case.  ‘qr.solve’ can
     handle non-square systems.

     Unsuccessful results from the underlying LAPACK code will result
     in an error giving a positive error code: these can only be
     interpreted by detailed study of the FORTRAN code.

_S_o_u_r_c_e:

     The default method is an interface to the LAPACK routines ‘DGESV’
     and ‘ZGESV’.

     LAPACK is from <URL: http://www.netlib.org/lapack>.

_R_e_f_e_r_e_n_c_e_s:

     Anderson. E. and ten others (1999) _LAPACK Users' Guide_. Third
     Edition. SIAM.
     Available on-line at <URL:
     http://www.netlib.org/lapack/lug/lapack_lug.html>.

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘solve.qr’ for the ‘qr’ method, ‘chol2inv’ for inverting from the
     Choleski factor ‘backsolve’, ‘qr.solve’.

_E_x_a_m_p_l_e_s:

     hilbert <- function(n) { i <- 1:n; 1 / outer(i - 1, i, "+") }
     h8 <- hilbert(8); h8
     sh8 <- solve(h8)
     round(sh8 %*% h8, 3)
     
     A <- hilbert(4)
     A[] <- as.complex(A)
     ## might not be supported on all platforms
     try(solve(A))